// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0i3IUkE9ImIdXbS7M04AMRnKb3SmVys',
    appId: '1:427419254549:web:1d0e81fb8569fa2700b31c',
    messagingSenderId: '427419254549',
    projectId: 'auth-task-b2848',
    authDomain: 'auth-task-b2848.firebaseapp.com',
    storageBucket: 'auth-task-b2848.appspot.com',
    measurementId: 'G-J67D6YMFG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wZx1oucYoLeWHA_o9TXmDmab52B8_X0',
    appId: '1:427419254549:android:8f7870085109f1fd00b31c',
    messagingSenderId: '427419254549',
    projectId: 'auth-task-b2848',
    storageBucket: 'auth-task-b2848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3RzF1YxWbp372jBLeGAEFp1n-hPD4P5w',
    appId: '1:427419254549:ios:0212b7df35bf827000b31c',
    messagingSenderId: '427419254549',
    projectId: 'auth-task-b2848',
    storageBucket: 'auth-task-b2848.appspot.com',
    iosBundleId: 'com.example.authTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3RzF1YxWbp372jBLeGAEFp1n-hPD4P5w',
    appId: '1:427419254549:ios:0212b7df35bf827000b31c',
    messagingSenderId: '427419254549',
    projectId: 'auth-task-b2848',
    storageBucket: 'auth-task-b2848.appspot.com',
    iosBundleId: 'com.example.authTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0i3IUkE9ImIdXbS7M04AMRnKb3SmVys',
    appId: '1:427419254549:web:29cc437f0a79001500b31c',
    messagingSenderId: '427419254549',
    projectId: 'auth-task-b2848',
    authDomain: 'auth-task-b2848.firebaseapp.com',
    storageBucket: 'auth-task-b2848.appspot.com',
    measurementId: 'G-T7NV1GBW8B',
  );
}
